import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { QueryClient, dehydrate } from "@tanstack/react-query";
import { fetcher } from "@/utils/fetcher";
import { Todo } from "@prisma/client";
import { dehydratedState } from "@/lib/react-query/dehydratedState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vimo",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const todo = await dehydratedState({ queryKey: ["todo"], path: "/api/todo" });
  const todo2 = await dehydratedState({
    queryKey: ["todo2"],
    path: "/api/todo",
  });

  return (
    <html lang="ja">
      <body className={`${inter.className} text-slate-700 bg-slate-100`}>
        <div className="w-[92%] max-w-[1024px] mx-auto mt-3 xs:mt-7 xs:w-[88%] sm:mt-9">
          <Provider todo={todo} todo2={todo2}>
            <Header />
            <div className="mt-12">{children}</div>
          </Provider>
        </div>
      </body>
    </html>
  );
}
